#!/usr/bin/env bash
# This script is displaying number 1-100
# Displays "Fizz" when number is multiple of 3
# Displays "Buzz" when number is multiple of 5
# Displays "FizzBuzz" when number is multiple of 3 and 5
i=1
while [ "$i" -lt 101 ];
do
    if [[ $(( i % 3)) -eq 0 && $(( i % 5 )) -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [ $(( i % 3 )) -eq 0 ]
    then
        echo "Fizz"
    elif [ $(( i % 5 )) -eq 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    ((i++))
done
