#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# It displays "Hi" in 9th iteration 
a=0
while [ $a -lt 11 ];
do
    if [ $a -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((a++))
done
