#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# It displays "bad luck from China" in 4th number
# It displays "bad luck from Japan" in 9th number
# It displays "bad luck from Italy" in 17th number
a=1
while [ "$a" -lt 21 ];
do
    case "$a" in
        4)
            echo "$a"
            echo "bad luck from China"
	    ;;
        9)
            echo "$a"
            echo "bad luck from Japan"
	    ;;
        17)
            echo "$a"
            echo "bad luck from Italy"
	    ;;
	*)
            echo "$a"
            ;;
    esac
    ((a++))
done
