#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/^127.0.0.*$/"127.0.0.2	localhost"/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
echo "8.8.8.8	facebook.com" >> /etc/hosts
